version: "3.3"

services:
  server:
    build: './server'
    ports: 
    - "4000:4000"
    networks:
    - backend
    depends_on:
    - database
    volumes:
    - ./server:/home/node/server
    - /home/node/server/node_modules
  database:
    image: "mongo"
    networks:
    - backend
    ports:
    - "27017:27017"

networks:
  backend:
